apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-tech-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyz-tech
  template:
    metadata:
      labels:
        app: xyz-tech
    spec:
      containers:
      - name: xyz-app
        image: rustamrustamov/xyz_tech:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            ephemeral-storage: "50Mi"
          limits:
            ephemeral-storage: "200Mi"
