---
- name: Deploy app to Kubernetes
  hosts: localhost
  connection: local
  vars:
    kubeconfig: "/var/snap/microk8s/current/credentials/client.config"  
    workspace: "{{ lookup('env', 'WORKSPACE') | default('.') }}"

  tasks:
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        src: "{{ workspace }}/deployment.yaml"
        remote_src: true  
      command: kubectl apply -f "{{ workspace }}/deployment.yaml" -v=10  # Adding verbose output

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        src: "{{ workspace }}/service.yaml"
      command: kubectl apply -f "{{ workspace }}/service.yaml" -v=10  # Adding verbose output
