---
- name: Build and push Docker image
  hosts: localhost
  connection: local
  vars:
    image_name: "rustamrustamov/xyz_tech"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') | default('latest') }}"
    workspace: "{{ lookup('env', 'WORKSPACE') | default('.') }}"
    dockerhub_user: "{{ dockerhub_user | default('') }}"
    dockerhub_pass: "{{ dockerhub_pass | default('') }}"

  tasks:
    - name: Login to DockerHub
      community.docker.docker_login:
        username: "{{ dockerhub_user }}"
        password: "{{ dockerhub_pass }}"

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ build_number }}"
        source: build
        build:
          path: "{{ workspace }}"
        push: no

    - name: Tag Docker image as latest
      command: docker tag {{ image_name }}:{{ build_number }} {{ image_name }}:latest

    - name: Push Docker image with build number tag
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ build_number }}"
        source: local
        push: yes

    - name: Push Docker image with latest tag
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        source: local
        push: yes
