---
- name: Deploy app to Kubernetes
  hosts: localhost
  connection: local
  vars:
    kubeconfig: "{{ lookup('env', 'kubeconfig') }}"
    workspace : "{{ lookup('env', 'WORKSPACE') | default('.') }}"

  tasks:
    - name: Apply Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state     : present
        src       : "{{ workspace }}/deployment.yaml"

    - name: Apply Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state     : present
        src       : "{{ workspace }}/service.yaml"
