apiVersion: v1
kind: Service
metadata:
  name: xyz-nodeport-svc
  namespace: default         
spec:
  type: NodePort
  selector:
    app: xyz-tech
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
